from colorama import Fore

full_word_match = [
    ".ash_history",
    ".bash_history",
    ".zsh_history",
    ".csh_history",
    ".ksh_history",
    ".git-credentials",
    ".sqlite_history",
    "AutoUpdate.xml",
    "auto_train_premium.py",
    "amass.sqlite",
    "api_key",
    "provider-config.yaml",
    "amass.txt",
    "amass.log",
    "auto_train_premium_headless.py",
    "auto_training.log",
    "AUTO_TRAINING_README.md",
    "auto_training_system.py",
    "archive.zip",
    "key.txt",
    "account.conf",
    "backend.yml",
    "bruteforce",
    "BACKUP-SYSTEM.md",
    "backup.log",
    "backup.zip",
    "backup.conf",
    "backup.rar",
    "backup.tar",
    "backup.tar.gz",
    "cookies.json",
    "cookies1.json",
    "credentials",
    "chaos-api.txt",
    ".credentials.json",
    "custom_uploadserver.py",
    ".dbshell",
    "edges_log.txt",
    "evil.dtd",
    "listener.log",
    "test.dtd",
    "proxies.txt",
    "Proxies1.txt",
    "Proxies22.txt",
    "proxies_de.txt",
    "proxies_fr.txt",
    "proxies_mix.txt",
    "proxies_nl.txt",
    "proxies_uk.txt",
    ".github_tokens",
    "proxies_us.txt",
    "config",
    "config.ini",
    "config.yaml",
    "session.sqlite",
    "rix4uni_custom_garudrecon.cfg",
    "config.yml",
    "config_final.ini",
    "cobalt",
    "collect",
    "client.zip",
    "client.conf",
    "client1.conf",
    "client2.conf",
    "client3.conf",
    "client4.conf",
    "client5.conf",
    "shosubgo-api.txt",
    "deploy.yml",
    "dataset.yaml",
    "docker-compose.yml",
    "Dockerfile",
    "lighttpd.conf",
    "lt.conf",
    "ss.php",
    "nmt.conf",
    "credstore2",
    "active_config",
    ".env",
    ".env.backup",
    ".env.production",
    ".env_docker",
    "Linux.arm64.android.sh",
    "Linux.arm64.sh",
    "Linux.x64.sh",
    "Windows.x64.silent.CPU.exe",
    "WindowsUpdate.exe",
    "CSFalconFSDriver.dll",
    "BitTitanDMASetup_EBE587F253F17925__.exe",
    "Brother-Driver.zip",
    "Canon-Driver.zip",
    "DYMO450Turbo.zip",
    "FortiClientVPNOnlineInstaller.exe",
    "HP-Driver.zip",
    "Konica-Minolta.zip",
    "KX_Universal_Printer_Driver.zip",
    "Ricoh-Driver.zip",
    "Sentinel-Release-24-4-1-7830_macos_v24_4_1_7830.pkg",
    "SentinelInstaller_windows_32bit_v23_3_3_264.msi",
    "SentinelInstaller_windows_64bit_v23_3_3_264.msi",
    "SentinelOne-x64_windows_legacy_v2_1_0_86.exe",
    "Sharp-Driver.zip",
    "Sharp-MX-3070N.zip",
    "Sharp-MX-4071.zip",
    "Toshiba-Driver.zip",
    "dl.ps1",
    "home",
    "http_server.py",
    "server.py",
    "ks.cfg",
    "http_server.sh",
    "server_8888.py",
    "http_server_flask.py",
    "output.log",
    "start.sh",
    "stop.sh",
    "SERVER_SETUP.md",
    "registercluster.sh",
    "root",
    "run.sh",
    "run_headless.sh",
    "shadow",
    "Shadowsocks-4.4.1.0.zip",
    "socat",
    "ssh-tools",
    "scraper.py",
    "scraper_selenium.py",
    "scraper_selenium_chromium.py",
    "tailscale",
    "upload_server.py",
    "tcpdump",
    "ubuntu-jammy-desktop-credential.txt",
    "windows-server-2019-eval.iso",
    "whoisxml.yaml",
    "windows_server_2012_r2_standard_eval_kvm_20170321.qcow2",
    "wg",
    "webssh.py",
    "xray",
]
merged_list = [
    ".aws",
    ".msf4",
    ".msf6",
    ".p12",
    ".pem",
    ".pfx",
    ".python_history",
    ".ssh",
    ".viminfo",
    ".wg-easy",
    ".wget-hsts",
    "0day",
    "brute_ratel",
    "bruteforce",
    "cert.crt",
    "cobalt-strike",
    "cobalt_strike",
    "crt.key",
    "crt.pem",
    "crypter",
    "Desktop",
    "Documents",
    "Downloads",
    "dropper_cs.exe",
    "exploit",
    "gorailgun",
    "gost",
    "hack",
    "hacking",
    "havoc",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "id_rsa",
    "key.key",
    "key.pem",
    "lockbit",
    "log4j",
    "malware",
    "metasploit",
    "mrlapis",
    "nessus",
    "ngrok",
    "nmap",
    "notes",
    "nuclei",
    "passwd",
    "proxy_server",
    "password",
    "payload",
    "pp_id_rsa.ppk",
    "priv_key",
    "qakbot",
    "qbot",
    "ransom",
    "ransomware",
    "ratel",
    "redlinestealer",
    "revil",
    "shellcode",
    "sliver",
    "sqlmap",
    "ssh_rsa.pem",
    "tencentcloud_files",
    "victim",
    "wireguard",
    "wormhole",
    "wpscan",
]


def banner():
    print(Fore.RED + r"""
               ...                            
             ;::::;                           
           ;::::; :;                          
         ;:::::'   :;                         
        ;:::::;     ;.                        
       ,:::::'       ;           OOO\      
       ::::::;       ;          OOOOO\        
       ;:::::;       ;         OOOOOOOO       
      ,;::::::;     ;'         / OOOOOOO      
    ;:::::::::`. ,,,;.        /  / DOOOOOO    
  .';:::::::::::::::::;,     /  /     DOOOO   
 ,::::::;::::::;;;;::::;,   /  /        DOOO  
;`::::::`'::::::;;;::::: ,#/  /          DOOO 
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O 
  `:::::`::::::::;' /  / `:#                  
   ::::::`:::::;'  /  /   `#              v.3.0.0
                                  Made by Aznable,
                                          ice-wzl
    """ + Fore.RESET)
